#!/bin/bash
# OMNIBOT v2.5 - Quick Commands Reference

echo "OMNIBOT v2.5 - Quick Commands"
echo "=============================="
echo ""
echo "SETUP:"
echo "  ./setup.sh                    - Run initial setup"
echo "  python src/main.py --setup    - Configure API keys"
echo ""
echo "TRADING:"
echo "  python src/main.py --mode cli - Start paper trading"
echo "  python src/main.py --trades   - View recent trades"
echo ""
echo "SERVICE (if installed):"
echo "  sudo systemctl start omnibot  - Start bot"
echo "  sudo systemctl stop omnibot   - Stop bot"
echo "  sudo systemctl status omnibot - Check status"
echo "  sudo journalctl -u omnibot -f - View live logs"
echo ""
echo "MAINTENANCE:"
echo "  source venv/bin/activate      - Activate Python environment"
echo "  deactivate                    - Exit environment"
echo "  htop                          - Monitor system resources"
echo ""
